image: mcr.microsoft.com/dotnet/sdk:latest

variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '*/obj/project.assets.json'
    - '*/obj/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

build:
  before_script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY SGL.Analytics.sln'
  stage: build
  script:
    - 'dotnet build --configuration ${CONFIG} --no-restore SGL.Analytics.sln'
  parallel:
    matrix:
      - CONFIG: [Debug, Release]
  artifacts:
    expire_in: 2 days
    paths:
      - 'bin/${CONFIG}/'
      - '*/bin/${CONFIG}/'

test:
  stage: test
  script:
    - 'dotnet test --no-restore --no-build --configuration Debug --test-adapter-path:. --logger:"junit;LogFilePath=../TestResults/{assembly}.xml;MethodFormat=Class;FailureBodyFormat=Verbose" SGL.Analytics.sln'
  artifacts:
    when: always
    paths:
     - ./TestResults/*.xml
    reports:
      junit:
       - ./TestResults/*.xml