image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - docbuild
  - test
  - package
  - deploy

variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '*/obj/project.assets.json'
    - '*/obj/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY SGL.Analytics.sln'

.build:
  stage: build
  script:
    - 'dotnet build --configuration ${CONFIG} --no-restore SGL.Analytics.sln'

build-debug:
  extends: .build
  variables:
    CONFIG: Debug
  artifacts:
    expire_in: 2 days
    paths:
      - SGL.Analytics.*/bin/Debug/*/SGL.Analytics.*.xml
      - SGL.Analytics.*/bin/Debug/*/SGL.Analytics.*.dll

build-release:
  extends: .build
  variables:
    CONFIG: Release

test:
  stage: test
  script:
    - 'rm -f */TestResults/*/coverage.cobertura.xml'
    - 'dotnet test --no-restore --configuration Debug --collect:"XPlat Code Coverage" --test-adapter-path:. --logger:"junit;LogFilePath=../TestResults/{assembly}.xml;MethodFormat=Class;FailureBodyFormat=Verbose" SGL.Analytics.sln'
  artifacts:
    expire_in: 14 days
    when: always
    paths:
     - ./TestResults/*.xml
     - '*/TestResults/*/coverage.cobertura.xml'
    reports:
      junit:
       - ./TestResults/*.xml
      cobertura:
       - '*/TestResults/*/coverage.cobertura.xml'

docs:
  stage: docbuild
  image: ${CI_REGISTRY}/serious-games-lab/docfx-ci-build-image
  before_script: []
  script:
    - docfx docfx_project/docfx.json
  artifacts:
    expire_in: 14 days
    paths:
      - docfx_output

.package-client-lib:
  stage: package
  script:
    - 'cd SGL.Analytics.Client'
    - 'dotnet pack -c Release -p:Version="$(git describe --tags --abbrev=0)${VERSION_SUFFIX}"'
    - 'dotnet nuget add source "${CI_API_V4_URL}/projects/${PACKAGE_REPO_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text'
    - 'dotnet nuget push "bin/Release/*.nupkg" --source gitlab --symbol-source gitlab'

package-client-lib-main:
  extends: .package-client-lib
  variables:
    GIT_DEPTH: 0
    VERSION_SUFFIX: "-dev"
  only:
    - main

package-client-lib-tags:
  extends: .package-client-lib
  variables:
    GIT_DEPTH: 0
    VERSION_SUFFIX: ""
  only:
    - tags
