image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test
  - package
  - deploy

variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '*/obj/project.assets.json'
    - '*/obj/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY SGL.Analytics.sln'

build:
  stage: build
  script:
    - 'dotnet build --configuration ${CONFIG} --no-restore SGL.Analytics.sln'
  parallel:
    matrix:
      - CONFIG: [Debug, Release]

test:
  stage: test
  script:
    - 'rm -f */TestResults/*/coverage.cobertura.xml'
    - 'dotnet test --no-restore --configuration Debug --collect:"XPlat Code Coverage" --test-adapter-path:. --logger:"junit;LogFilePath=../TestResults/{assembly}.xml;MethodFormat=Class;FailureBodyFormat=Verbose" SGL.Analytics.sln'
  artifacts:
    expire_in: 14 days
    when: always
    paths:
     - ./TestResults/*.xml
     - '*/TestResults/*/coverage.cobertura.xml'
    reports:
      junit:
       - ./TestResults/*.xml
      cobertura:
       - '*/TestResults/*/coverage.cobertura.xml'

include:
- template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
- local: '/package.gitlab-ci.yml'
