image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
  - package
  - deploy

variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - '*/obj/project.assets.json'
    - '*/obj/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

before_script:
  - 'dotnet nuget update source SGL --username ${SGL_PKG_USER} --password ${SGL_PKG_TOKEN} --store-password-in-clear-text'
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY SGL.Analytics.sln'

after_script:
  - 'dotnet nuget update source SGL --username dummy --password dummy --store-password-in-clear-text'

.build:
  needs: []
  stage: build
  script:
    - 'dotnet build --configuration ${CONFIG} --no-restore SGL.Analytics.sln'

build-debug:
  extends: .build
  variables:
    CONFIG: Debug
  artifacts:
    expire_in: 2 days
    paths:
      - SGL.Analytics.*/bin/Debug/*/SGL.Analytics.*.xml
      - SGL.Analytics.*/bin/Debug/*/SGL.Analytics.*.dll

build-release:
  extends: .build
  variables:
    CONFIG: Release

test:
  stage: test
  needs: []
  script:
    - 'rm -f */TestResults/*/coverage.cobertura.xml'
    - 'dotnet test -f net6.0 --no-restore --configuration Debug --collect:"XPlat Code Coverage" --test-adapter-path:. --logger:"junit;LogFilePath=../TestResults/{assembly}.xml;MethodFormat=Class;FailureBodyFormat=Verbose" SGL.Analytics.sln'
  artifacts:
    expire_in: 14 days
    when: always
    paths:
     - ./TestResults/*.xml
     - '*/TestResults/*/coverage.cobertura.xml'
    reports:
      junit:
       - ./TestResults/*.xml
      coverage_report:
        coverage_format: cobertura
        path: '*/TestResults/*/coverage.cobertura.xml'

docs:
  stage: build
  needs:
  - build-debug
  image: ${CI_REGISTRY}/serious-games-lab/docfx-ci-build-image
  before_script: []
  script:
    - docfx docfx_project/docfx.json
  artifacts:
    name: "SGL.Analytics.Docs"
    expire_in: 14 days
    paths:
      - docfx_output

client-docs:
  stage: build
  needs:
  - build-debug
  image: ${CI_REGISTRY}/serious-games-lab/docfx-ci-build-image
  before_script: []
  script:
    - docfx docfx_project/docfx_client_only.json
  artifacts:
    name: "SGL.Analytics.ClientDocs"
    expire_in: 14 days
    paths:
      - docfx_output
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

pages:
  stage: deploy
  needs:
  - docs
  before_script: []
  script:
    - rm -rf public
    - mv docfx_output public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

include:
- template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
- local: '/package.gitlab-ci.yml'

deploy-shg-test:
  stage: deploy
  inherit:
    variables: false
  variables:
    SGL_ANALYTICS_IMAGE_TAG: "main"
  needs:
  - pkg-docker-main
  - deployment-package
  trigger:
    project: serious-games-lab/senior-health-games/sgl-analytics-deployment
    branch: main
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-upm:
  stage: deploy
  inherit:
    variables: false
  variables:
    SGL_ANALYTICS_VERSION: $SGL_ANALYTICS_VERSION
    SGL_ANALYTICS_REF: $CI_COMMIT_REF_NAME
  needs:
  - nuget-package
  trigger:
    project: serious-games-lab/sgl-analytics-unity
    branch: main
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^\d+(\.\d+)*$/'
    - if: $FORCE_NUGET_BUILD
