version: '3.4'

services:
  app-registrations:
    labels:
      com.microsoft.visualstudio.debuggee.arguments: "--additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net5.0/SGL.Analytics.Backend.AppRegistrationTool.dll\" push /app/definitions"
    image: sgl-analytics-app-registration:vs-release
  db:
    image: sgl-analytics-db:vs-release
  logs-collector-migrations:
    container_name: SGL.Analytics.Backend.Logs.Collector-Migrations
    image: sgl-analytics-logs-collector:vs-release-migrations
    entrypoint: ["wait-for-it", "-s", "-t", "120", "db:5432", "--", "psql", "-h", "db", "-U", "sgla_logs", "-f", "/DbMigrations.sql"]
    build:
      target: final
  users-registration-migrations:
    container_name: SGL.Analytics.Backend.Users.Registration-Migrations
    image: sgl-analytics-users-registration:vs-release-migrations
    entrypoint: ["wait-for-it", "-s", "-t", "120", "db:5432", "--", "psql", "-h", "db", "-U", "sgla_users", "-f", "/DbMigrations.sql"]
    build:
      target: final
  logs-collector-app:
    image: sgl-analytics-logs-collector:vs-release
  users-registration-app:
    image: sgl-analytics-users-registration:vs-release
  api-gateway:
    image: sgl-analytics-api-gateway:vs-release
