version: '3.4'

networks:
  proxy:
    external: true

volumes:
  db-data:
   driver_opts:
         type: none
         device: /var/sgl/analytics/database
         o: bind
  game-logs:
   driver_opts:
         type: none
         device: /var/sgl/analytics/gamelogs
         o: bind
  log-collector-log-files:
   driver_opts:
         type: none
         device: /var/log/SGL.Analytics.LogCollector
         o: bind
  user-registration-log-files:
   driver_opts:
         type: none
         device: /var/log/SGL.Analytics.UserRegistration
         o: bind
  test-upstream-backend-log-files:
   driver_opts:
         type: none
         device: /var/log/SGL.Analytics.Test.Upstream
         o: bind
  app-definitions:
   driver_opts:
         type: none
         device: /var/sgl/analytics/app-definitions
         o: bind
  log-collector-conf:
   driver_opts:
         type: none
         device: /var/sgl/analytics/conf/LogCollector
         o: bind
  user-registration-conf:
   driver_opts:
         type: none
         device: /var/sgl/analytics/conf/UserRegistration
         o: bind
  test-upstream-backend-conf:
   driver_opts:
         type: none
         device: /var/sgl/analytics/conf/TestUpstreamBackend
         o: bind

services:
  app-registrations:
    environment:
    - DOTNET_ENVIRONMENT=Staging
    volumes:
    - "app-definitions:/app/definitions"
  logs-collector-app:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Logging__Console__LogLevel__SGL.Utilities.Backend.AspNetCore.Authentication=Warning
      - Logging__Console__LogLevel__SGL.Analytics.Backend.Logs.Application.Services.LogManager=Warning
  users-registration-app:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Logging__Console__LogLevel__SGL.Utilities.Backend.Security.JwtLoginService=Warning
  api-gateway:
    profiles:
    - DontLaunchOnStaging
  db:
    restart: unless-stopped
  jwt-secret-key-gen:
    # set restart to ensure a restart at host boot to generate a key in the cleared tmpfs.
    restart: unless-stopped
  test-upstream-backend:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
