version: '3.4'

services:
  db:
    build:
      context: SGL.Analytics.Backend.DB
      dockerfile: Dockerfile
      target: final
  logs-collector-migrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Logs.Collector/Dockerfile
      target: final
      args:
        SGL_PKG_USER:
        SGL_PKG_TOKEN:
  users-registration-migrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Users.Registration/Dockerfile
      target: final
      args:
        SGL_PKG_USER:
        SGL_PKG_TOKEN:
  app-registrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.AppRegistrationTool/Dockerfile
      target: final
      args:
        SGL_PKG_USER:
        SGL_PKG_TOKEN:
  logs-collector-app:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Logs.Collector/Dockerfile
      target: final
      args:
        SGL_PKG_USER:
        SGL_PKG_TOKEN:
  users-registration-app:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Users.Registration/Dockerfile
      target: final
      args:
        SGL_PKG_USER:
        SGL_PKG_TOKEN:
  api-gateway:
    build:
      context: SGL.Analytics.Backend.APIGW
      dockerfile: Dockerfile
      target: final
