version: '3.4'

services:
  db:
    build:
      context: SGL.Analytics.Backend.DB
      dockerfile: Dockerfile
  logs-collector-migrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Logs.Collector/Dockerfile
  users-registration-migrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Users.Registration/Dockerfile
  app-registrations:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.AppRegistrationTool/Dockerfile
  logs-collector-app:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Logs.Collector/Dockerfile
  users-registration-app:
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Users.Registration/Dockerfile
  api-gateway:
    build:
      context: SGL.Analytics.Backend.APIGW
      dockerfile: Dockerfile
