volumes:
  db-data:
    driver_opts:
      type: none
      device: /var/sgl/analytics/database
      o: bind
  game-logs:
    driver_opts:
      type: none
      device: /var/sgl/analytics/gamelogs
      o: bind
  log-collector-log-files:
    driver_opts:
      type: none
      device: /var/log/SGL.Analytics.LogCollector
      o: bind
  user-registration-log-files:
    driver_opts:
      type: none
      device: /var/log/SGL.Analytics.UserRegistration
      o: bind
  app-definitions:
    driver_opts:
      type: none
      device: /var/sgl/analytics/app-definitions
      o: bind
  log-collector-conf:
    driver_opts:
      type: none
      device: /var/sgl/analytics/conf/LogCollector
      o: bind
  user-registration-conf:
    driver_opts:
      type: none
      device: /var/sgl/analytics/conf/UserRegistration
      o: bind
  https-certs:
    driver_opts:
      type: none
      device: /var/sgl/analytics/ssl-certs
      o: bind

services:
  app-registrations:
    environment:
    - DOTNET_ENVIRONMENT=Production
    volumes:
    - "app-definitions:/app/definitions"
  logs-collector-app:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  users-registration-app:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  api-gateway:
    volumes:
      - "https-certs:/etc/ssl/my:ro"
    restart: unless-stopped
  db:
    restart: unless-stopped
  jwt-secret-key-gen:
    # set restart to ensure a restart at host boot to generate a key in the cleared tmpfs.
    restart: unless-stopped
  test-upstream-backend:
    profiles:
    - DontLaunchOnProd
