version: '3.4'

services:
  app-registrations:
    environment:
    - DOTNET_ENVIRONMENT=Development
    volumes:
    - "./SGL.Analytics.Backend.AppRegistrationTool/Dev-Definitions:/app/definitions"

  logs-collector-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - FileSystemLogRepository__StorageDirectory=/var/game-logs
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  users-registration-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  api-gateway:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "vs_certs:/etc/ssl/my"
    entrypoint: ["/use_vs_cert.sh"]
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - VS_CERT_SECRET_ID=fb10d495-0e38-4cea-b398-a7dd25f58472
      - VS_CERT_NAME=SGL.Analytics.Backend.Logs.Collector

volumes:
  vs_certs:
