version: '3.4'

services:
  app-registrations:
    labels:
      com.microsoft.visualstudio.debuggee.arguments: "--additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/SGL.Analytics.Backend.AppRegistrationTool.dll\" push /app/definitions"
    image: sgl-analytics-app-registration:vs-debug
  db:
    image: sgl-analytics-db:vs-debug
  logs-collector-migrations:
    container_name: SGL.Analytics.Backend.Logs.Collector-Migrations
    image: sgl-analytics-logs-collector:vs-debug-migrations
    entrypoint: ["/bin/sh","-c","wait-for -t 120 db:5432 -- psql -h db -U sgla_logs_admin -d sgla_logs -f /DbMigrations.sql && tail -f /dev/null"]
    build:
      target: final
  users-registration-migrations:
    container_name: SGL.Analytics.Backend.Users.Registration-Migrations
    image: sgl-analytics-users-registration:vs-debug-migrations
    entrypoint: ["/bin/sh","-c","wait-for -t 120 db:5432 -- psql -h db -U sgla_users_admin -d sgla_users -f /DbMigrations.sql && tail -f /dev/null"]
    build:
      target: final
  logs-collector-app:
    image: sgl-analytics-logs-collector:vs-debug
  users-registration-app:
    image: sgl-analytics-users-registration:vs-debug
  test-upstream-backend:
    image: test-upstream-backend:vs-debug
  api-gateway:
    image: sgl-analytics-api-gateway:vs-debug
