version: '3.4'

services:
  db:
    image: ${DOCKER_REGISTRY-}sglanalytics/db
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.DB/Dockerfile
    environment:
      USERREG_PW:
      LOGS_PW:
      POSTGRES_PASSWORD:
  
  sgl.analytics.backend.logs.collector:
    image: ${DOCKER_REGISTRY-}sglanalytics/logs-collector
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Logs.Collector/Dockerfile
    environment:
      ConnectionStrings__LogsContext:
    depends_on:
    - db

  sgl.analytics.backend.users.registration:
    image: ${DOCKER_REGISTRY-}sglanalytics/users-registration
    build:
      context: .
      dockerfile: SGL.Analytics.Backend.Users.Registration/Dockerfile
    environment:
      ConnectionStrings__UsersContext:
    depends_on:
    - db
    