services:
  app-registrations:
    environment:
    - DOTNET_ENVIRONMENT=Development
    - ConnectionStrings__LogsContext
    - ConnectionStrings__UsersContext
    volumes:
    - "./SGL.Analytics.Backend.AppRegistrationTool/Dev-Definitions:/app/definitions"

  logs-collector-app:
    environment:
      - ConnectionStrings__LogsContext
      - ASPNETCORE_ENVIRONMENT=Development
      - FileSystemLogRepository__StorageDirectory=/var/game-logs
      - Logging__File__BaseDirectory=/var/log/SGL.Analytics.LogCollector
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  users-registration-app:
    environment:
      - ConnectionStrings__UsersContext
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__File__BaseDirectory=/var/log/SGL.Analytics.UserRegistration
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  api-gateway:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "vs_certs:/etc/ssl/my"
    entrypoint: ["/use_vs_cert.sh"]
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - VS_CERT_SECRET_ID=fb10d495-0e38-4cea-b398-a7dd25f58472
      - VS_CERT_NAME=SGL.Analytics.Backend.Logs.Collector
  test-upstream-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__File__BaseDirectory=/var/log/SGL.Analytics.Test.Upstream
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  vs_certs:
