.package-client-lib:
  stage: package
  script:
    - 'cd SGL.Analytics.Client'
    - 'dotnet pack -c Release -p:Version="$(git describe --tags --abbrev=0)${VERSION_SUFFIX}"'
    - 'dotnet nuget add source "${CI_API_V4_URL}/projects/${PACKAGE_REPO_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text'
    - 'dotnet nuget push "bin/Release/*.nupkg" --source gitlab --symbol-source gitlab'

package-client-lib-main:
  extends: .package-client-lib
  variables:
    GIT_DEPTH: 0
    VERSION_SUFFIX: "-dev"
  only:
    - main

package-client-lib-tags:
  extends: .package-client-lib
  variables:
    GIT_DEPTH: 0
    VERSION_SUFFIX: ""
  only:
    - tags

.package-backend-docker-images:
  stage: package
  variables:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: ${CI_PROJECT_DIR}/docker_ci_cache
  services:
  - registry:2
  before_script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  cache:
    paths:
    - 'docker_ci_cache'
  script:
  - BUILD_OPTS="--cleanup --cache=true --insecure-registry=registry:5000 --cache-repo=registry:5000/cache --context ${CI_PROJECT_DIR} --dockerfile ${PACKAGE_IMAGE_DIR}/Dockerfile --target final"
  - /kaniko/executor $BUILD_OPTS --destination "${PACKAGE_IMAGE}:${PACKAGE_IMAGE_TAG_1}" --destination "${PACKAGE_IMAGE}:${PACKAGE_IMAGE_TAG_2}" --destination "${PACKAGE_IMAGE}:${CI_COMMIT_SHORT_SHA}"

package-backend-docker-images:
  extends: .package-backend-docker-images
  variables:
    PACKAGE_IMAGE_TAG_1: ${CI_COMMIT_REF_SLUG}
    PACKAGE_IMAGE_TAG_2: latest
  parallel:
    matrix:
    - IMAGE_NAME: LogsCollector
      PACKAGE_IMAGE_DIR: "SGL.Analytics.Backend.Logs.Collector"
      PACKAGE_IMAGE: "${CI_REGISTRY_IMAGE}/logs-collector"
    - IMAGE_NAME: UsersRegistration
      PACKAGE_IMAGE_DIR: "SGL.Analytics.Backend.Users.Registration"
      PACKAGE_IMAGE: "${CI_REGISTRY_IMAGE}/users-registration"
    - IMAGE_NAME: AppRegistrationTool
      PACKAGE_IMAGE_DIR: "SGL.Analytics.Backend.AppRegistrationTool"
      PACKAGE_IMAGE: "${CI_REGISTRY_IMAGE}/app-registration"
    - IMAGE_NAME: DB
      PACKAGE_IMAGE_DIR: "SGL.Analytics.Backend.DB"
      PACKAGE_IMAGE: "${CI_REGISTRY_IMAGE}/db"
    - IMAGE_NAME: APIGW
      PACKAGE_IMAGE_DIR: "SGL.Analytics.Backend.APIGW"
      PACKAGE_IMAGE: "${CI_REGISTRY_IMAGE}/api-gateway"
